---
title: "RWorksheet_Nava#3a"
author: "Samantha Nicole Nava"
date: "2024-09-30"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
USING VECTORS
```{r}
LETTERS <- c ("A", "B", "C", "D" ,"E" ,"F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z")
 
letters <- c ("a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s","t", "u", "v", "w", "x", "y", "z")

```
1.
a.
```{r}
first_eleven <- head(LETTERS, 11)
first_eleven
```
b.
```{r}
odd_numberedL <- LETTERS[seq(1,26, by=2)]
odd_numberedL
```
c.
```{r}
vowels <- LETTERS[LETTERS %in% c("A","E","I","O","U")]
vowels
```
d.
```{r}
lowercase <- tail(letters, 5)
lowercase
```
e.
```{r}
lcase_1524 <- letters[15:24]
lcase_1524
```
2.
a.
```{r}
city <- c("Tuguegarao City", "Manila", "Iloilo City", "Tacloban", "Samal Island", "Davao City")
city
```
b.
```{r}
temp <- c("42","39","34","34","30", "27")
temp
```
c.
```{r}
city_temp <- data.frame(city, temp)
city_temp
```
d.
```{r}
names(city_temp) <-c("City", "Temperature")
city_temp
```
e.
```{r}
str(city_temp)
```
f.
```{r}
city_temp[3:4,]
```
g.
```{r}
highesttempcity <- city_temp[which.max(city_temp$Temperature), ]
highesttempcity

```
```{r}
lowesttempcity <- city_temp[which.min(city_temp$Temperature), ]
lowesttempcity
```
MATRICES
2.
a
```{r}
matrix_1 <- matrix(c(1:8, 11:14), nrow = 3, ncol = 4, byrow = TRUE)
matrix_1
```
b.
```{r}
matrix_2 <- matrix_1 * 2
matrix_2
```
c.
```{r}
matrix_1[2, ]

```
d.
```{r}
matrix_1[1:2, 3:4]
```
e.
```{r}
matrix_1[3, 2:3]
```
f.
```{r}
matrix_1[, 4]

```
g.
```{r}
# Name rows and columns
rownames(matrix_2) <- c("isa", "dalawa", "tatlo")
colnames(matrix_2) <- c("uno", "dos", "tres", "quatro")
matrix_2
```
h.
```{r}
dim(matrix_1) <- c(6, 2)
matrix_1
```
ARRAYS
3.
a.
```{r}
values <- rep(c(1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1), times = 2)
array <- array(values, dim = c(2, 4, 3))
array
```
b.
```{r}
dim(array)

```
c.
```{r}
dimnames(array) <- list(
c("a", "b"),
c("A", "B", "C", "D"),
c("1st-Dimensional Array", "2nd-Dimensional Array", "3rd-Dimensional Array")
)
array
```

